### ISSUE TITLE
Error run with armv7 ？(v1.10.4)

### ISSUE THREAD

**Issue by yangyang5214** [twmb/franz-go#286]
Error in  👇 ?
if atomic.AddInt64(&p.bufferedRecords, 1) > cl.cfg.maxBufferedRecords {
xxxx
}

```
panic: unaligned 64-bit atomic operation

goroutine 37 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x18c6254, 0x1)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/twmb/franz-go/pkg/kgo.(*Client).produce(0x18c6000, {0x63be48, 0x14a6000}, 0x17465b0, 0x5a80e4, 0x1)
	/root/go/pkg/mod/github.com/twmb/franz-go@v1.10.4/pkg/kgo/producer.go:381 +0xd4
github.com/twmb/franz-go/pkg/kgo.(*Client).Produce(...)
	/root/go/pkg/mod/github.com/twmb/franz-go@v1.10.4/pkg/kgo/producer.go:355
pvp-agent/net.(*KafkaEmit).Start.func1(0x14faa40, 0x14f8720)
	/opt/pvp-agent/src/net/kafka_emit.go:74 +0x3b4
created by pvp-agent/net.(*KafkaEmit).Start
	/opt/pvp-agent/src/net/kafka_emit.go:28 +0xd8
exit status 2

```

**Comment by yangyang5214** [comment]
https://github.com/twmb/franz-go/blob/master/pkg/kgo/producer.go#L17 

```
bufferedRecords int64 //  May be refer WaitGroup?   (I'm new at golang 😊.)


atomic.AddInt64(&p.bufferedRecords, 1)  // error in this line
```


- WaitGroup
```
type WaitGroup struct {
	noCopy noCopy

	// 64-bit value: high 32 bits are counter, low 32 bits are waiter count.
	// 64-bit atomic operations require 64-bit alignment, but 32-bit
	// compilers only guarantee that 64-bit fields are 32-bit aligned.
	// For this reason on 32 bit architectures we need to check in state()
	// if state1 is aligned or not, and dynamically "swap" the field order if
	// needed.
	state1 uint64
	state2 uint32
}

// state returns pointers to the state and sema fields stored within wg.state*.
func (wg *WaitGroup) state() (statep *uint64, semap *uint32) {
	if unsafe.Alignof(wg.state1) == 8 || uintptr(unsafe.Pointer(&wg.state1))%8 == 0 {
		// state1 is 64-bit aligned: nothing to do.
		return &wg.state1, &wg.state2
	} else {
		// state1 is 32-bit aligned but not 64-bit aligned: this means that
		// (&state1)+4 is 64-bit aligned.
		state := (*[3]uint32)(unsafe.Pointer(&wg.state1))
		return (*uint64)(unsafe.Pointer(&state[1])), &state[0]
	}
}
```

**Comment by twmb** [comment]
This linter should be preventing what you're seeing: https://github.com/twmb/franz-go/actions/runs/3682375289/jobs/6229958927

https://pkg.go.dev/sync/atomic#pkg-note-BUG
"The first word in an allocated struct, array, or slice; in a global variable; or in a local variable (because the subject of all atomic operations will escape to the heap) can be relied upon to be 64-bit aligned."

**Comment by yangyang5214** [comment]
I found that my comment was incorrect, so I deleted  before [Flushed]

Thank you so much for the quick investigation and the insight! 


----

It's worked, when checkout  version to v1.9.0 😊

<img width="664" alt="image" src="https://user-images.githubusercontent.com/23392325/207502627-0c88e550-f103-486e-868c-4b7dff59ce73.png">

**Comment by twmb** [comment]
Good to see you have 1.9.0 working. Does 1.10.4 not work for you? I don't think anything significantly changed in these code paths, but I could take a look (also not sure why the linter would be passing on both versions)

**Comment by yangyang5214** [comment]
yeah,

- v1.9.1    work 
- v1.10.0+  not work


/root/go/pkg/mod/github.com/twmb/franz-go@v1.10.0/pkg/kgo/producer.go:381 +0xd4 (v1.10.0)

```
panic: unaligned 64-bit atomic operation

goroutine 35 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x2fe6254, 0x1)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/twmb/franz-go/pkg/kgo.(*Client).produce(0x2fe6000, {0x633800, 0x2d1c000}, 0x308a700, 0x2c9f180, 0x1)
	/root/go/pkg/mod/github.com/twmb/franz-go@v1.10.0/pkg/kgo/producer.go:381 +0xd4
github.com/twmb/franz-go/pkg/kgo.(*Client).Produce(...)
	/root/go/pkg/mod/github.com/twmb/franz-go@v1.10.0/pkg/kgo/producer.go:355
pvp-agent/net.(*KafkaEmit).Start.func1(0x2d72a40, 0x2d70720)
	/opt/pvp-agent/src/net/kafka_emit.go:74 +0x3b0
created by pvp-agent/net.(*KafkaEmit).Start
	/opt/pvp-agent/src/net/kafka_emit.go:28 +0xd8
exit status 2
```

**Comment by twmb** [comment]
Candidate problems:
a995b1b kgo broker: retry sasl auth failures during reauthentication -- not likely, just a retry in broker code
6bbe188 consumer group: clarify log line -- not likely, just a log line fix
dcfcacb {Cooperative,Sticky}Balancer: bug fix lack of stickiness -- not likely, bug fix in unrelated code
76430a8 kgo: add option to consume preferring laggy partitions -- perhaps related? adds one field to the config, but other than that, entirely unrelated
cf392a3 kgo: bump FetchRequest to v13, add test to ensure we always track latest -- not likely, this is just bumping fetch request to v13 (and apparently adding some cruft that is removed in the next commit)
8ab8074 kgo connection: always allow one request after SASL -- not likely, this is just retrying in broker.go
9ac6c97 kgo: support forward & backward batch requests for FindCoordinator, OffsetFetch -- potentially related? should be unrelated, code changed only in client.go and broker.go
b4a4c05 kgo: return guessed tls misconfiguration -- unlikely, this is just returning information in a struct

Can you try checking out v1.10.0, reverting 76430a8, and then seeing if that fixes things? I wonder if, where the sync/atomic BUG notice says "first word in an allocated struct", it means that embedded structs are not aligned (_only_ allocated structs, not non-allocated structs embedded in an allocated struct)

**Comment by yangyang5214** [comment]
Checkout to  **76430a8**,  then move producer var to  first in Client struct,  it work


```

➜ git checkout 76430a8

➜  franz-go git:(76430a8) ✗ git status
HEAD detached at 76430a8
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   pkg/kgo/client.go


➜  franz-go git:(76430a8) ✗ git diff pkg/kgo/client.go

 type Client struct {
-       cfg cfg
+       producer producer
+       cfg      cfg
 
        ctx       context.Context
        ctxCancel func()
@@ -72,7 +73,6 @@ type Client struct {
                err  error
        }
 
-       producer producer
        consumer consumer

```


![image](https://user-images.githubusercontent.com/23392325/207589835-560b9f65-4ac2-4eda-9861-c142556d796c.png)

**Comment by twmb** [comment]
the solution above I'm not sure is completely reliable. Instead, I've added build files such that Go 1.19+ uses Go's atomics, which are special cased in the compiler. That should resolve this permanently. Please take a look at the incoming 1.11 (within a few hours)

**Comment by twmb** [comment]
Released
