### ISSUE TITLE
SIGSEGV in fetchRequest.AppendTo, might be related to ConsumePreferringLagFn

### ISSUE THREAD

**Issue by brunsgaard** [twmb/franz-go#310]
Hi Travis, 

We are experiencing panics in our consumer right now. It _seems_ only to be an issue when `ConsumePreferringLagFn` is being used. We had the consumers offline for an hour, when we redeployed this started. Please advice.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbd9f4b]

goroutine 25322 [running]:
github.com/twmb/franz-go/pkg/kgo.(*fetchRequest).AppendTo(0xc0fca9c3c0, {0xc00e5c0800, 0xf, 0x400})
	/go/pkg/mod/github.com/twmb/franz-go@v1.11.0/pkg/kgo/source.go:1815 +0x8ab
github.com/twmb/franz-go/pkg/kmsg.(*RequestFormatter).AppendRequest(0xc000466b10, {0xc00e5c0800?, 0x19249c0?, 0x0?}, {0x1204f20, 0xc0fca9c3c0}, 0x4)
	/go/pkg/mod/github.com/twmb/franz-go/pkg/kmsg@v1.2.0/api.go:233 +0x3c9
github.com/twmb/franz-go/pkg/kgo.(*brokerCxn).writeRequest(0xc002c00400, {0x11ffc40, 0xc001de50c0}, {0x1204f20?, 0xc0fca9c3c0?, 0x19249c0?}, {0x1204f20, 0xc0fca9c3c0})
	/go/pkg/mod/github.com/twmb/franz-go@v1.11.0/pkg/kgo/broker.go:1006 +0x425
github.com/twmb/franz-go/pkg/kgo.(*broker).handleReq(0xc0005cdb80, {{0x11ffc40, 0xc001de50c0}, {0x1204f20, 0xc0fca9c3c0}, 0xc001980540, {0xc0ea180e93b3bd4f, 0x395ea367b, 0x19249c0}})
	/go/pkg/mod/github.com/twmb/franz-go@v1.11.0/pkg/kgo/broker.go:428 +0xa8d
github.com/twmb/franz-go/pkg/kgo.(*broker).handleReqs(0xc0005cdb80, {{0x11ffc40, 0xc001de50c0}, {0x1204f20, 0xc0fca9c3c0}, 0xc001980540, {0xc0ea180e93b3bd4f, 0x395ea367b, 0x19249c0}})
	/go/pkg/mod/github.com/twmb/franz-go@v1.11.0/pkg/kgo/broker.go:273 +0xbd
created by github.com/twmb/franz-go/pkg/kgo.(*broker).do
	/go/pkg/mod/github.com/twmb/franz-go@v1.11.0/pkg/kgo/broker.go:247 +0x229
```

Are there any information we can provide that will help you debug these panics?

CC: @jepp2078

**Comment by twmb** [comment]
(hopefully) Fixed in v1.11.1
