### ISSUE TITLE
Kafka NullPointerException on fetch

### ISSUE THREAD

**Issue by alistairking** [twmb/franz-go#535]
Howdy!

Since we upgraded our Kafka cluster to 3.5.1 (from 2.7.0) we've frequently been seeing errors like this:
```
[2023-08-09 15:02:04,003] ERROR [KafkaApi-4] Unexpected error handling request RequestHeader(apiKey=FETCH, apiVersion=15, clientId=kgo, correlationId=29, headerVersion=2) -- FetchRequestData(clusterId
=null, replicaId=-1, replicaState=ReplicaState(replicaId=-1, replicaEpoch=-1), maxWaitMs=5000, minBytes=1, maxBytes=52428800, isolationLevel=0, sessionId=606347500, sessionEpoch=29, topics=[], forgottenTopicsData=[ForgottenTopic(topic='', topicId=AAAAAAAAAAAAAAAAAAAAAA, partitions=[0])], rackId='') with context RequestContext(header=RequestHeader(apiKey=FETCH, apiVersion=15, clientId=kgo, correlationId=29, headerVersion=2), connectionId='10.99.108.16:9192-10.88.7.32:63300-535', clientAddress=/10.88.7.32, principal=User:ANONYMOUS, listenerName=ListenerName(INSIDE), securityProtocol=PLAINTEXT, clientInformation=ClientInformation(softwareName=unknown, softwareVersion=unknown), fromPrivilegedListener=true, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@7efc7797]) (kafka.server.KafkaApis)
java.lang.NullPointerException
```

I'm not at all sure this is franz-go's fault, but given that it's complaining about handling a request I thought that just maybe the client is doing something wrong.

**Comment by twmb** [comment]
Does this come when you're closing a client?
Did this ever happen before?
What are the kgo logs around the time?

**Comment by twmb** [comment]
This might be another instance of https://github.com/twmb/franz-go/issues/295
I solved 295 only for partitions that are added to fetch requests,
but a partition that is "forgotten" and removed, I think there's a gap in my logic.

**Comment by alistairking** [comment]
We upgraded from 2.7.0, inter-broker is set to 3.5

No clients were being closed at the time, but there's a decent chance that new topics/partitions were created recently (not deleted however).

As for kgo logs, there's a bunch of things like
```
immediate metadata update triggered
fetch had inner topic errors: FENCED_LEADER_EPOCH{....
```
and
```
resetting fetch session
INVALID_FETCH_SESSION_EPOCH: The fetch session epoch is invalid.
```

**Comment by alistairking** [comment]
Yep, I should be able to do that.

**Comment by alistairking** [comment]
I'm still working on getting the relevant debug logs, but this just happened again, and our entire kafka cluster crashed.

Here's a sample of the errors we got from kafka in case they're interesting:
```
[2023-08-09 18:40:01,468] ERROR [ReplicaFetcher replicaId=4, leaderId=6, fetcherId=8] Error for partition xxx-0>
org.apache.kafka.common.errors.KafkaStorageException: Disk error when trying to access log file on the disk.
java.io.IOException: Connection to 6 was disconnected before the response was read
        at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
        at kafka.server.BrokerBlockingSender.sendRequest(BrokerBlockingSender.scala:113)
        at kafka.server.RemoteLeaderEndPoint.fetch(RemoteLeaderEndPoint.scala:79)
        at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:316)
        at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:130)
        at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:129)
        at scala.Option.foreach(Option.scala:437)
        at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:129)
        at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:112)
        at kafka.server.ReplicaFetcherThread.doWork(ReplicaFetcherThread.scala:98)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)
```
and
```
[2023-08-09 18:48:27,710] ERROR Closing socket for 10.3.108.16:9192-10.2.22.42:48218-9 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: PRODUCE, apiVersion: 9, connectionId: 10.3.108.16:9192-10.2.22.42:48218-9, listenerName: ListenerName(INSIDE), principal:User:ANONYMOUS
Caused by: java.lang.IllegalArgumentException: Varint is too long, the most significant bit in the 5th byte is set, converted value: b645ea89
        at org.apache.kafka.common.utils.ByteUtils.illegalVarintException(ByteUtils.java:453)
        at org.apache.kafka.common.utils.ByteUtils.readUnsignedVarint(ByteUtils.java:160)
        at org.apache.kafka.common.protocol.ByteBufferAccessor.readUnsignedVarint(ByteBufferAccessor.java:70)
        at org.apache.kafka.common.message.ProduceRequestData$TopicProduceData.read(ProduceRequestData.java:545)
        at org.apache.kafka.common.message.ProduceRequestData$TopicProduceData.<init>(ProduceRequestData.java:464)
        at org.apache.kafka.common.message.ProduceRequestData.read(ProduceRequestData.java:172)
        at org.apache.kafka.common.message.ProduceRequestData.<init>(ProduceRequestData.java:114)
        at org.apache.kafka.common.requests.ProduceRequest.parse(ProduceRequest.java:256)
        at org.apache.kafka.common.requests.AbstractRequest.doParseRequest(AbstractRequest.java:171)
        at org.apache.kafka.common.requests.AbstractRequest.parseRequest(AbstractRequest.java:165)
        at org.apache.kafka.common.requests.RequestContext.parseRequest(RequestContext.java:95)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:102)
        at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1148)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
        at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1126)
        at kafka.network.Processor.run(SocketServer.scala:1012)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
and
```
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because the return value of "kafka.server.CachedPartition.topic()" is null
```

**Comment by twmb** [comment]
The entire cluster crashing is definitely a Kafka problem...
To know which line that is requires generating the serializers/deserializers in the Kafka source.

**Comment by alistairking** [comment]
Of course I haven't been able to reproduce this after I added the debug logging. It's possible it happens on partition creation, so I'll try that next week.

**Comment by alistairking** [comment]
Ok, it looks like this error pops up just after we signal a broker to shut down (e.g., during a rolling restart). Now that I know how to reproduce I should be able to get debug logs later this week.

**Comment by twmb** [comment]
Any luck reproducing?

**Comment by alistairking** [comment]
Yes and no. I've managed to reproduce it a few times now (indeed it pops up when we restart a broker), but I lost the build I had running that had debug logs enabled.
Sorry for the delay, I've been fighting a bunch of fires this week. I'll try and get the debug build back out there next week and repro.

**Comment by twmb** [comment]
I am fairly certain I see the bug, wip to fix.

**Comment by twmb** [comment]
If you're able, can you try this branch?
https://github.com/twmb/franz-go/compare/535
