### ISSUE TITLE
Another kafka NullPointerException on fetch

### ISSUE THREAD

**Issue by alistairking** [twmb/franz-go#620]
This seems similar (though not identical from what I can tell) to #535.

After upgrading our Kafka cluster to 3.6.0, we see these errors pop up from time to time.
Other than the upgrade, we've also been rebalancing some topics over to new nodes. Otherwise, the producer/consumer side of things is untouched.

```
[2023-11-17 17:09:33,147] ERROR [KafkaApi-1] Unexpected error handling request RequestHeader(apiKey=FETCH, apiVersion=15, clientId=kgo, correlationId=1, headerVersion=2) -- FetchRequestData(clusterId=
null, replicaId=-1, replicaState=ReplicaState(replicaId=-1, replicaEpoch=-1), maxWaitMs=5000, minBytes=1, maxBytes=52428800, isolationLevel=0, sessionId=34235446, sessionEpoch=1, topics=[FetchTopic(topic='', topicId=mlj9qJNqQ5Wz0nH8B-Xn2Q, partitions=[FetchPartition(partition=0, currentLeaderEpoch=7, fetchOffset=0, lastFetchedEpoch=-1, logStartOffset=-1, partitionMaxBytes=1048576)])], forgottenTopicsData=[ForgottenTopic(topic='', topicId=AAAAAAAAAAAAAAAAAAAAAA, partitions=[0])], rackId='') with context RequestContext(header=RequestHeader(apiKey=FETCH, apiVersion=15, clientId=kgo, correlationId=1, headerVersion=2), connectionId='10.9.108.16:9062-10.8.23.32:63412-54', clientAddress=/10.8.23.32, principal=User:ANONYMOUS, listenerName=ListenerName(EXTERNAL), securityProtocol=PLAINTEXT, clientInformation=ClientInformation(softwareName=unknown, softwareVersion=unknown), fromPrivilegedListener=false, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@ef9f51d]) (kafka.server.KafkaApis)
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because the return value of "kafka.server.CachedPartition.topic()" is null
        at kafka.server.CachedPartition.hashCode(FetchSession.scala:185)
        at org.apache.kafka.common.utils.ImplicitLinkedHashCollection.slot(ImplicitLinkedHashCollection.java:309)
        at org.apache.kafka.common.utils.ImplicitLinkedHashCollection.findIndexOfEqualElement(ImplicitLinkedHashCollection.java:327)
        at org.apache.kafka.common.utils.ImplicitLinkedHashCollection.findElementToRemove(ImplicitLinkedHashCollection.java:475)
        at org.apache.kafka.common.utils.ImplicitLinkedHashCollection.remove(ImplicitLinkedHashCollection.java:466)
        at kafka.server.FetchSession.$anonfun$update$2(FetchSession.scala:289)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at kafka.server.FetchSession.update(FetchSession.scala:288)
        at kafka.server.FetchManager.newContext(FetchSession.scala:836)
        at kafka.server.KafkaApis.handleFetchRequest(KafkaApis.scala:726)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:181)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:149)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by twmb** [comment]
I think #627 should address this. This was certainly an oversight in my original fix of forgotten topics.

**Comment by alistairking** [comment]
Amazing. Thank you for figuring this out.
